Repository hypothesis/client, pull requests merged in 2020-04, with the labels that each got.

#1993 Remove annotation-mapper service and associated Angular events
  src/sidebar/components/annotation-action-bar.js
  src/sidebar/components/annotation-viewer-content.js
  src/sidebar/components/hypothesis-app.js
  src/sidebar/components/stream-content.js
  src/sidebar/components/test/annotation-action-bar-test.js
  src/sidebar/components/test/annotation-viewer-content-test.js
  src/sidebar/components/test/hypothesis-app-test.js
  src/sidebar/components/test/stream-content-test.js
  src/sidebar/events.js
  src/sidebar/index.js
  src/sidebar/services/annotation-mapper.js
  src/sidebar/services/annotations.js
  src/sidebar/services/load-annotations.js
  src/sidebar/services/root-thread.js
  src/sidebar/services/streamer.js
  src/sidebar/services/test/annotation-mapper-test.js
  src/sidebar/services/test/annotations-test.js
  src/sidebar/services/test/load-annotations-test.js
  src/sidebar/services/test/root-thread-test.js
  src/sidebar/services/test/streamer-test.js
Labels: Angular migration

#2014 Update Preact
  package.json
  src/sidebar/util/test/wrap-react-component-test.js
  yarn.lock
Labels: dependencies

#2072 Do not use `button` element in `Menu` label
  src/sidebar/components/sort-menu.js
  src/sidebar/components/user-menu.js
  src/styles/sidebar/components/top-bar.scss
Labels: accessibility
