Repository hypothesis/client, pull requests merged in 2020-01, with the labels that each got.

#1611 Fix datalist performance in Chrome
  src/sidebar/components/tag-editor.js
  src/sidebar/components/test/tag-editor-test.js
  src/sidebar/services/tags.js
  src/sidebar/services/test/tags-test.js
Labels: P2: Urgent, bug

#1656 Normalize module imports to an ES module-friendly format
  src/annotator/anchoring/test/html-test.js
  src/annotator/test/integration/multi-frame-test.js
  src/boot/index.js
  src/sidebar/components/test/annotation-test.js
  src/sidebar/directive/test/h-branding-test.js
  src/sidebar/index.js
  src/sidebar/services/frame-sync.js
  src/sidebar/services/oauth-auth.js
  src/sidebar/services/test/frame-sync-test.js
  src/sidebar/store/create-store.js
  src/sidebar/store/modules/groups.js
  src/sidebar/store/modules/real-time-updates.js
  src/sidebar/store/modules/selection.js
  src/sidebar/test/bootstrap.js
  src/sidebar/util/test/retry-test.js
Labels: ES modules

#1658 Hoist CommonJS imports to top of file
  src/sidebar/components/test/annotation-viewer-content-test.js
  src/sidebar/components/test/hypothesis-app-test.js
  src/sidebar/components/test/sidebar-content-test.js
  src/sidebar/components/test/stream-content-test.js
  src/sidebar/directive/test/h-on-touch-test.js
  src/sidebar/directive/test/h-tooltip-test.js
  src/sidebar/index.js
  src/sidebar/services/test/annotation-mapper-test.js
  src/sidebar/services/test/oauth-auth-test.js
  src/sidebar/services/test/search-filter-test.js
  src/sidebar/services/test/session-test.js
  src/sidebar/services/test/tags-test.js
  src/sidebar/services/test/unicode-test.js
  src/sidebar/test/integration/threading-test.js
Labels: ES modules

#1660 Convert sidebar entry point to ES modules
  src/sidebar/index.js
Labels: ES modules

#1673 Convert src/sidebar/services to ES modules
  src/sidebar/services/analytics.js
  src/sidebar/services/annotation-mapper.js
  src/sidebar/services/annotations.js
  src/sidebar/services/api-routes.js
  src/sidebar/services/api.js
  src/sidebar/services/features.js
  src/sidebar/services/flash.js
  src/sidebar/services/frame-sync.js
  src/sidebar/services/groups.js
  src/sidebar/services/local-storage.js
  src/sidebar/services/oauth-auth.js
  src/sidebar/services/permissions.js
  src/sidebar/services/root-thread.js
  src/sidebar/services/search-filter.js
  src/sidebar/services/service-url.js
  src/sidebar/services/session.js
  src/sidebar/services/stream-filter.js
  src/sidebar/services/streamer.js
  src/sidebar/services/tags.js
  src/sidebar/services/test/analytics-test.js
  src/sidebar/services/test/annotation-mapper-test.js
  src/sidebar/services/test/annotations-test.js
  src/sidebar/services/test/api-routes-test.js
  src/sidebar/services/test/api-test.js
  src/sidebar/services/test/features-test.js
  src/sidebar/services/test/flash-test.js
  src/sidebar/services/test/frame-sync-test.js
  src/sidebar/services/test/groups-test.js
  src/sidebar/services/test/local-storage-test.js
  src/sidebar/services/test/oauth-auth-test.js
  src/sidebar/services/test/permissions-test.js
  src/sidebar/services/test/root-thread-test.js
  src/sidebar/services/test/search-filter-test.js
  src/sidebar/services/test/service-url-test.js
  src/sidebar/services/test/session-test.js
  src/sidebar/services/test/stream-filter-test.js
  src/sidebar/services/test/streamer-test.js
  src/sidebar/services/test/tags-test.js
  src/sidebar/services/test/unicode-test.js
  src/sidebar/services/test/view-filter-test.js
  src/sidebar/services/unicode.js
  src/sidebar/services/view-filter.js
  src/sidebar/test/integration/threading-test.js
Labels: ES modules

#1674 Convert src/sidebar/store to ES modules
  src/sidebar/store/create-store.js
  src/sidebar/store/debug-middleware.js
  src/sidebar/store/index.js
  src/sidebar/store/modules/activity.js
  src/sidebar/store/modules/annotations.js
  src/sidebar/store/modules/direct-linked.js
  src/sidebar/store/modules/drafts.js
  src/sidebar/store/modules/frames.js
  src/sidebar/store/modules/groups.js
  src/sidebar/store/modules/links.js
  src/sidebar/store/modules/real-time-updates.js
  src/sidebar/store/modules/selection.js
  src/sidebar/store/modules/session.js
  src/sidebar/store/modules/sidebar-panels.js
  src/sidebar/store/modules/test/activity-test.js
  src/sidebar/store/modules/test/annotations-test.js
  src/sidebar/store/modules/test/direct-linked-test.js
  src/sidebar/store/modules/test/drafts-test.js
  src/sidebar/store/modules/test/frames-test.js
  src/sidebar/store/modules/test/groups-test.js
  src/sidebar/store/modules/test/links-test.js
  src/sidebar/store/modules/test/real-time-updates-test.js
  src/sidebar/store/modules/test/selection-test.js
  src/sidebar/store/modules/test/session-test.js
  src/sidebar/store/modules/test/sidebar-panels-test.js
  src/sidebar/store/modules/test/viewer-test.js
  src/sidebar/store/modules/viewer.js
  src/sidebar/store/test/create-store-test.js
  src/sidebar/store/test/debug-middleware-test.js
  src/sidebar/store/test/index-test.js
  src/sidebar/store/test/use-store-test.js
  src/sidebar/store/test/util-test.js
  src/sidebar/store/use-store.js
  src/sidebar/store/util.js
Labels: ES modules

#1675 Convert src/sidebar/directives to ES modules
  src/sidebar/directive/h-autofocus.js
  src/sidebar/directive/h-branding.js
  src/sidebar/directive/h-on-touch.js
  src/sidebar/directive/h-tooltip.js
  src/sidebar/directive/test/h-branding-fixtures.js
  src/sidebar/directive/test/h-branding-test.js
  src/sidebar/directive/test/h-on-touch-test.js
  src/sidebar/directive/test/h-tooltip-test.js
  src/sidebar/directive/test/util.js
  src/sidebar/directive/test/window-scroll-test.js
  src/sidebar/directive/window-scroll.js
  src/sidebar/ga.js
  src/sidebar/util/scope-timeout.js
Labels: ES modules

#1681 Convert src/boot to ES modules
  src/boot/boot.js
  src/boot/index.js
  src/boot/test/boot-test.js
  src/boot/test/url-template-test.js
  src/boot/url-template.js
Labels: ES modules

#1680 Convert most modules in src/annotator to ES modules
  src/annotator/anchoring/pdf.js
  src/annotator/anchoring/test/fake-pdf-viewer-application.js
  src/annotator/anchoring/test/html-baselines/index.js
  src/annotator/anchoring/test/html-test.js
  src/annotator/anchoring/test/pdf-test.js
  src/annotator/anchoring/test/text-position-test.js
  src/annotator/anchoring/test/types-test.js
  src/annotator/anchoring/text-position.js
  src/annotator/config/config-func-settings-from.js
  src/annotator/config/index.js
  src/annotator/config/is-browser-extension.js
  src/annotator/config/settings.js
  src/annotator/config/test/config-func-settings-from-test.js
  src/annotator/config/test/index-test.js
  src/annotator/config/test/is-browser-extension-test.js
  src/annotator/config/test/settings-test.js
  src/annotator/index.js
  src/annotator/plugin/document.js
  src/annotator/plugin/pdf-metadata.js
  src/annotator/plugin/pdf.coffee
  src/annotator/plugin/test/document-test.js
  src/annotator/plugin/test/pdf-metadata-test.js
  src/annotator/plugin/test/toolbar-test.js
  src/annotator/test/adder-test.js
  src/annotator/test/annotation-counts-test.js
  src/annotator/test/annotation-sync-test.js
  src/annotator/test/features-test.js
  src/annotator/test/range-util-test.js
  src/annotator/test/selections-test.js
  src/annotator/test/sidebar-trigger-test.js
  src/annotator/util/frame-util.js
  src/annotator/util/observable.js
  src/annotator/util/url.js
Labels: ES modules

#1688 Convert src/shared/{polyfills, test, settings.js} to ES modules
  src/shared/polyfills/document.evaluate.js
  src/shared/polyfills/es2015.js
  src/shared/polyfills/es2016.js
  src/shared/polyfills/es2017.js
  src/shared/polyfills/fetch.js
  src/shared/polyfills/index.js
  src/shared/polyfills/string.prototype.normalize.js
  src/shared/polyfills/test/index-test.js
  src/shared/polyfills/url.js
  src/shared/settings.js
  src/shared/test/bridge-test.js
  src/shared/test/discovery-test.js
  src/shared/test/promise-util.js
  src/shared/test/settings-test.js
  src/shared/test/warn-once-test.js
Labels: ES modules

#1703 Convert remaining CommonJS modules to ES modules
  src/annotator/annotation-counts.js
  src/annotator/annotation-sync.js
  src/annotator/features.js
  src/annotator/frame-observer.js
  src/annotator/guest.coffee
  src/annotator/pdfjs-rendering-states.js
  src/annotator/plugin/cross-frame.coffee
  src/annotator/plugin/pdf.coffee
  src/annotator/selections.js
  src/annotator/sidebar-trigger.js
  src/annotator/sidebar.coffee
  src/annotator/test/sidebar-test.coffee
  src/shared/bridge-events.js
  src/shared/bridge.js
  src/shared/discovery.js
  src/shared/frame-rpc.js
  src/shared/warn-once.js
  src/sidebar/services/test/persisted-defaults-test.js
  yarn.lock
Labels: ES modules

#1729 Add accessibility unit test using axe-core
  package.json
  src/karma.config.js
  src/sidebar/components/logged-out-message.js
  src/sidebar/components/test/accessibility.js
  src/sidebar/components/test/annotation-action-bar-test.js
  src/sidebar/components/test/annotation-body-test.js
  src/sidebar/components/test/annotation-document-info-test.js
  src/sidebar/components/test/annotation-header-test.js
  src/sidebar/components/test/annotation-publish-control-test.js
  src/sidebar/components/test/annotation-quote-test.js
  src/sidebar/components/test/annotation-share-control-test.js
  src/sidebar/components/test/annotation-share-info-test.js
  src/sidebar/components/test/annotation-user-test.js
  src/sidebar/components/test/button-test.js
  src/sidebar/components/test/excerpt-test.js
  src/sidebar/components/test/focused-mode-header-test.js
  src/sidebar/components/test/help-panel-test.js
  src/sidebar/components/test/logged-out-message-test.js
  src/sidebar/components/test/markdown-editor-test.js
  src/sidebar/components/test/markdown-view-test.js
  src/sidebar/components/test/menu-item-test.js
  src/sidebar/components/test/menu-section-test.js
  src/sidebar/components/test/menu-test.js
  src/sidebar/components/test/moderation-banner-test.js
  src/sidebar/components/test/new-note-btn-test.js
  src/sidebar/components/test/search-input-test.js
  src/sidebar/components/test/search-status-bar-test.js
  src/sidebar/components/test/selection-tabs-test.js
  src/sidebar/components/test/share-annotations-panel-test.js
  src/sidebar/components/test/share-links-test.js
  src/sidebar/components/test/sidebar-content-error-test.js
  src/sidebar/components/test/sidebar-panel-test.js
  src/sidebar/components/test/slider-test.js
  src/sidebar/components/test/spinner-test.js
  src/sidebar/components/test/tag-editor-test.js
  src/sidebar/components/test/tag-list-test.js
  src/sidebar/components/test/timestamp-test.js
  src/sidebar/components/test/top-bar-test.js
  src/sidebar/components/test/tutorial-test.js
  src/sidebar/components/test/version-info-test.js
  yarn.lock
Labels: accessibility
